name: avatar_stack
description: Advanced and agile avatar stack with settings. It allows to place a lot of avatars or another widgets in small place.
maintainer: Alexander Bosak (bskaxe@gmail.com)
issue_tracker: https://github.com/cyrax111/avatar_stack/issues
repository: https://github.com/cyrax111/avatar_stack
version: 1.2.1

environment:
  sdk: ">=2.17.0 <3.0.0"
  # flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter: