name: avatar_stack
description: Advanced and agile avatar stack with settings. It allows to place a lot of avatars or another widgets in small place.
version: 0.3.0
repository: https://github.com/cyrax111/avatar_stack

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: